
name: Docker
on:
    push:
        tags: v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   name: Setup - gcloud / gsutil
                uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
                with:
                    service_account_key: ${{ secrets.ACTIONS_SERVICE_ACC }}
                    export_default_credentials: true
            -   name: Set default project
                run: |
                    gcloud config set core/project altethical
                    gcloud auth configure-docker
                    gcloud config set run/region us-central1
            -
              name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: |
                  gcr.io/joshcarp/cloud-spanner-emulator:latest
                  gcr.io/joshcarp/cloud-spanner-emulator:${{ github.ref }}
